---
- apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10

- template: src=mongodb-org-3.0.list dest=/etc/apt/sources.list.d/mongodb-org-3.0.list

- name: Install mongo
  apt: name=mongodb-org update_cache=yes
  async: 1800

- name: Bind mongo to localhost
  lineinfile: dest=/etc/mongod.conf regexp='^bind_ip\s*=\s*127\.0\.0\.1\s*' line='bind_ip = 127.0.0.1'

- service: name=mongod state=started

- name: Install pymongo for any project related mongo
  pip: name=pymongo
  async: 1800