#!/usr/bin/env bash

# source ~/.zshrc
. /home/{{ ansible_ssh_user }}/.zshrc

cd /home/{{ ansible_ssh_user }}/{{ project_name }} && bower install
npm install --production

PROJECT_STARTED=$(pm2 list | grep {{ project_name }})

echo "{{ project_name }} started: $PROJECT_STARTED"

if [ -z "$PROJECT_STARTED" ]
then
    pm2 start /home/{{ ansible_ssh_user }}/processes.json
    pm2 save
else
    pm2 restart {{ project_name }}
fi
